# Generated by Django 3.1.5 on 2021-01-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jutsu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='anime',
            name='head_img',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='anime',
            name='img',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='сharacter',
            name='img',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='сharacter',
            name='sag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='сharacter',
            name='side',
            field=models.CharField(max_length=100),
        ),
    ]
