# Generated by Django 3.1.5 on 2021-01-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jutsu', '0004_auto_20210109_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='сharacter',
            name='name_char',
            field=models.CharField(default='lol', max_length=50),
            preserve_default=False,
        ),
    ]
