# Generated by Django 3.1.5 on 2021-01-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_time', models.DateTimeField()),
                ('description', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('head_img', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Сharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sag', models.CharField(max_length=50)),
                ('side', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jutsu.anime')),
            ],
        ),
    ]
