# Generated by Django 3.1.5 on 2021-01-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jutsu', '0002_auto_20210108_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='release_time',
            field=models.CharField(max_length=10),
        ),
    ]
