# Generated by Django 3.1.5 on 2021-01-10 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jutsu', '0005_сharacter_name_char'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jutsu.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('animes', models.ManyToManyField(through='jutsu.Anime_Genre', to='jutsu.Anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jutsu.genre'),
        ),
    ]
