# Generated by Django 3.1.5 on 2021-01-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jutsu', '0006_auto_20210110_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.CharField(max_length=700),
        ),
    ]
